### ISSUE TITLE
Database Is Wiped Out On Every Run

### ISSUE THREAD

**Issue by StrangeWill** [sbadia/puppet-gitlab#215]
Fresh install on Debian 7, ${git_home}/.gitlab_setup_done is not being created, touching it fixes it. Not sure why...

**Comment by toepi** [comment]
Note: with version 0.1.5 and gitlab 6.9 it works on debian 7 like expected. My database (postgress on separate host) is alive since 4 month and puppet runs every 30 minutes. So it must introduced between 0.1.5 and 0.2.

**Comment by alexcern** [comment]
Hi

Same behavior here on Centos7. The cause is 9df87b7e6249ab35a7ec51186d4631e24205b20f removing ensure => present on File["${git_home}/.gitlab_setup_done"] because lint complained about it. Now the file is not created anymore and new installs will keep recreating the database.

I guess the way to keep lint happy and restore the correct behavior is to have ensure => file

**Comment by sbadia** [comment]
Indeed, sorry for this bug… Many thanks for the debug+patch!
